# Source dependancies
[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

# golang.org/x/* packages are not versioned
[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
