# Tools required for generating, liniting, and formatting code
required = [
  "github.com/golang/lint/golint",
  "github.com/golang/protobuf/protoc-gen-go",
  "golang.org/x/tools/cmd/goimports",
  "honnef.co/go/tools/cmd/megacheck",
  "github.com/wadey/gocovmerge"
]

# Source dependancies
[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

# golang.org/x/* packages are not versioned
[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
